In [2]:
import gym
env = gym.make('CartPole-v0').unwrapped
env.seed(0)
print(env.reset())
env.step(1)
# env.seed(0)
env.reset()

[-0.04456399  0.04653909  0.01326909 -0.02099827]


/Volumes/Macintosh_HD/Users/Aron/Documents/UvA/MSc Artificial Intelligence/Thesis/breaking_atari/.venv/lib/python3.5/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


array([-0.03975157,  0.01730763, -0.01074233,  0.01698461])

In [3]:
import numpy as np
bo = np.arange(10) > 3

In [7]:
(bo + 1) % 2

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [19]:
import torch

next_state_values = torch.zeros((128,))
non_final_mask = torch.ones((128,), dtype=torch.uint8)
non_final_mask[40] = 0
next_state_values[non_final_mask].shape

torch.Size([127])

In [29]:
import gym
from atari_wrappers import wrap_deepmind, LazyFrames

env = gym.make('SpaceInvadersDeterministic-v4')
env = wrap_deepmind(env, frame_stack=True)
obs = env.reset()
isinstance(obs, np.ndarray)

False

In [ ]:
torch.transpose()